# first, we print the list of students
puts "The students of my cohort at Makers Academy"
puts "-------------"
puts "Mario Gintili"
puts "Mikhail Dubov"
puts "Karolis Noreika"
puts "Michael Sidon"
puts "Charles De Barros"
puts "Ruslan Vikhor"
puts "Toby Retallick"
puts "Mark Mekhaiel"
puts "Sarah Young"
puts "Hannah Wight"
puts "Khushkaran Singh"
puts "Rick Brunstedt"
puts "Manjit Singh"
puts "Alex Gaudiosi"
puts "Ross Hepburn"
puts "Natascia Marchese"
puts "Tiffanie Chia"
puts "Matthew Thomas"
puts "Freddy McGroarty"
puts "Tyler Rollins"
puts "Richard Curteis"
puts "Anna Yanova"
puts "Andrew Cumine"
# finally, we print the total
print "Overall, we have "
# it's important that print() doesn't add new line characters
print 23 
puts " great students"